[package]
name = "rust-dl-heatmap-processing"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15.0"
env_logger = "0.11.7"
log = "0.4.27"
serde = "1.0.219"
serde_json = "1.0.140"
dicom = "0.5.4"
png = "0.17.7"
image = "0.25.1"
